version: '3.3'

services:
  nexus3:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    user: root
    volumes:
      - "nexus3-data-nginx:/opt/sonatype/sonatype-work/nexus3"

  nginx:
    image: nginx:latest
    volumes:
      - ./docker-nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-nginx-proxy/certs:/home
    depends_on:
      - nexus3
    ports:
      - "443:443"

volumes:
  nexus3-data-nginx:
